apiVersion: v1
kind: ConfigMap
metadata:
  name: player-service-config
  namespace: game-matchmaking
data:

  SPRING_PROFILES_ACTIVE: "prod"

  SPRING_DATA_MONGODB_URI: "mongodb://admin:admin123@mongodb-service:27017/playerdb?authSource=admin"

  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "admin"

  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_GAMING: "DEBUG"