apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: game-matchmaking
type: Opaque
stringData:
  mongodb-root-username: admin
  mongodb-root-password: admin123

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: game-matchmaking
type: Opaque
stringData:
  rabbitmq-username: admin
  rabbitmq-password: admin123